function results = investigationResults( names, path, ...
                                         parameters, values, setup, ...
                                         catchErrors, memorySaving, ...
                                         inParallel )

    if inParallel
        thisInvestigation = ParallelInvestigation( names, path, ...
                                       parameters, values, setup, ...
                                       catchErrors, memorySaving );
    else
        thisInvestigation = Investigation( names, path, ...
                                       parameters, values, setup, ...
                                       catchErrors, memorySaving );
    end

    thisInvestigation = thisInvestigation.run;

    thisInvestigation.saveDataPlot;
    results = thisInvestigation.saveReport;

    thisInvestigation.save( memorySaving = memorySaving );

end