function results = investigationResults( names, path, ...
                                         parameters, values, setup, ...
                                         memorySaving, resume )

    thisRun = Investigation( names, path, ...
                             parameters, values, setup, ...
                             memorySaving, resume );
    results = thisRun.getResults;

end