function mbq = getMiniBatchQueue( self, batchSize, XLabels, XNLabels, args )
    % Create a minibatch queue
    arguments
        self                ModelDataset
        batchSize           double ...
            {mustBeInteger, mustBePositive}
        XLabels             char
        XNLabels            char
        args.lengthOrder    logical = false
        args.partialBatch   char ...
            {mustBeMember( args.partialBatch, ...
            {'return', 'discard'} )} = 'discard'
    end

    if args.lengthOrder
        % sort in ascending order of length
        XLen = cellfun( @length, self.XInput );
        [ ~, orderIdx ] = sort( XLen, 'descend' );
    else
        orderIdx = [];
    end

    % setup the minibatch preprocessing function
    preproc = @( X, XN, Y ) preprocMiniBatch( X, XN, Y, ...
                  self.Padding.Value, ...
                  self.Padding.Location, ...
                  self.Perplexity );

    mbq = BatchQueue(  self.XInput, self.XTarget, self.Y, ...
                       IterDim = [1, 2, 1], ...
                       NumOutputs = 4, ...
                       BatchSize = batchSize, ...
                       BatchFcn = preproc, ...
                       BatchFormat = {XLabels, XNLabels, 'CB', 'CB'}, ...
                       ResetOrder = orderIdx );

end