function mbq = getMiniBatchQueue( self, batchSize, XLabels, XNLabels, args )
    % Create a minibatch queue
    arguments
        self                ModelDataset
        batchSize           double ...
            {mustBeInteger, mustBePositive}
        XLabels             char
        XNLabels            char
        args.partialBatch   char ...
            {mustBeMember( args.partialBatch, ...
            {'return', 'discard'} )} = 'discard'
    end

    ds = createDatastore( self.XInput, self.XTarget, self.Y );

    % setup the minibatch preprocessing function
    preproc = @( X, XN, Y ) preprocMiniBatch( X, XN, Y, ...
                  self.Padding.Value, ...
                  self.Padding.Location, ...
                  self.Perplexity );

    mbq = minibatchqueue(  ds, 4, ...
          MiniBatchSize = batchSize, ...
          PartialMiniBatch = args.partialBatch, ...
          MiniBatchFcn = preproc, ...
          MiniBatchFormat = {XLabels, XNLabels, 'CB', 'CB'} );

end