function [fig, ax] = plotModelsFStat(models, names)
    % This function takes a cell array of mixed generalized linear models,
    % generated by fitglme, and produces a single bar chart with different
    % colored bars for each model, grouped by the horizontal axis labels.
    % The function returns the figure handle and the axes handles.
    %
    % Usage: [fig, ax] = plotFittedModels(models)
    %
    % Input:
    % - models: a cell array containing mixed generalized linear models
    %
    % Output:
    % - fig: handle to the created figure
    % - ax: handles to the created axes
    % Author:
    % - GPT4
    arguments
        models          cell
        names           string
    end
    
    
    % Check if the input is a cell array of models
    numModels = numel(models);
    if ~iscell(models) || numModels < 1 || numModels > 4
        error('The input must be a cell array containing between 1 and 4 mixed generalized linear models.');
    end
    if numModels ~= numel(names)
        error('The names do not match the models.');
    end
    
    % Collect all variable names from the models
    allVariables = {};
    for i = 1:numModels
        anovaResults = dataset2table( anova(models{i}) );
        modelVariables = anovaResults.Term;
        allVariables = union(allVariables, modelVariables, 'stable');
    end
    
    % Create the figure and the 2x2 tile layout
    fig = figure;
    ax = axes(fig);
    
    % Initialize the F statistics matrix with NaNs
    numVar = numel(allVariables);
    Fstats = nan(numVar, numModels);

    % Loop through the models and populate the F statistics matrix
    for i = 1:numModels
        anovaResults = dataset2table(anova(models{i}));
        modelVariables = anovaResults.Term;

        % Loop through the variables in the current model
        for j = 1:numel(modelVariables)
            idx = strcmp(modelVariables{j}, allVariables);
            Fstats(idx, i) = anovaResults.FStat(j);
        end
    end

    % Plot the grouped bar chart
    b = bar(ax, Fstats, 'grouped');
    set(ax, 'XTick', 1:numVar, 'XTickLabel', allVariables, 'XTickLabelRotation', 45);
    ylabel(ax, 'F statistic');

    % Set the y-axis scale to log10
    ax.YScale = 'log';

    % Add a legend to identify the models
    legend(ax, b, names, 'Location', 'best');

    % Add a ylabel for the plot
    ax.YLabel.String = 'F statistic (log scale)';
    ax.XLabel.String = 'Hyperparameters';

end





