function dlXC = calcLatentComponents( self, dlZ, args )
    % Calculate the funtional components 
    % introducing the option to convert to single
    arguments
        self                AEModel
        dlZ                 dlarray
        args.convert        logical = false
    end

    % prepare the latent encoding
    switch self.ComponentType
        case 'PDP'
            dlZC = self.prepPDP( dlZ );
        case 'ALE'
            [ dlZC, A, w ] = self.prepALE( dlZ );
    end

    % construct the curves
    dlXCGen = self.reconstruct( dlZC );

    % generate the components
    switch self.ComponentType
        case 'PDP'
            dlXC = self.calcPDP( dlXCGen );
        case 'ALE'
            dlXC = self.calcALE( dlXCGen, A, w );
    end

    % put XC into the appropriate structure
    % Points, Samples, Components, Channels
    nSamples = size( dlXC, 2 );

    % extract the mean curve based on Z
    % (the central column has Z equal to the mean)
    XMean = dlXC( :, ceil(nSamples/2), :, : );
    
    switch self.ComponentCentering
        case 'Z'
            % centre about the curve generated by mean Z
            dlXC = dlXC - XMean;
        case 'X'
            % centre about the mean generated curve
            dlXC = dlXC - mean( dlXC, length(size(dlXC)) );
    end

    if args.convert
        if isa( dlXC, 'dlarray' )
            dlXC = double( extractdata( dlXC ) );
        end
    end

end
